// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kipclwwcfcpzinnuwhlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcGNsd3djZmNwemlubnV3aGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzUyMzksImV4cCI6MjA2MTYxMTIzOX0.Glcq_cMkweLE3GOhN6FEay70QLCRLzr8DhXY8q7Htn8";

// Add debugging for connectivity
console.log('Supabase client initialized with URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Export the URL for debugging purposes
export { SUPABASE_URL };